USE [db_zoo_1]
GO

SELECT * FROM TBL_HABITAT;

SELECT SPECIES_NAME FROM TBL_SPECIES WHERE SPECIES_ORDER = 3;

SELECT NUTRITION_TYPE, NUTRITION_COST FROM TBL_NUTRITION WHERE NUTRITION_COST <= 600;

SELECT SPECIES_NAME FROM TBL_SPECIES A1
	INNER JOIN TBL_NUTRITION A2 ON A1.SPECIES_NUTRITION = A2.NUTRITION_ID
	WHERE NUTRITION_ID BETWEEN 2202 AND 2206;

SELECT A1.SPECIES_NAME AS SPECIESNAME, A2.NUTRITION_TYPE AS [NUNTRITION TYPE] 
	FROM TBL_SPECIES A1
	INNER JOIN TBL_NUTRITION A2 ON A1.SPECIES_NUTRITION = A2.NUTRITION_ID;

SELECT A1.SPECIALIST_FNAME, A1.SPECIALIST_LNAME, A1.SPECIALIST_CONTACT
	FROM TBL_SPECIALIST A1
	INNER JOIN TBL_CARE A2 ON A2.CARE_SPECIALIST = A1.SPECIALIST_ID
	INNER JOIN TBL_SPECIES A3 ON A3.SPECIES_CARE = A2.CARE_ID
	WHERE A3.SPECIES_NAME = 'PENGUIN'

